title: Atharva Kulkarni
subtitle: Welcome to  my Portfolio Website
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I am Atharva Kulkarni

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Extras
      url : /extras
    - text: Facts
      url: /facts
    - text: Blog
      url: /blog
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: athu.png
author: Atharva Kulkarni
author_bio: I am a student currently living in Dallas, TX. My professional interests range from solving state of the art Machine Learning problems to spending my evenings on hackerrank.
author_email: "atharvak56@gmail.com"
author_location: Dallas, USA
author_website_url: "http://athuofficial.github.io"
typewrite-text: Atharva Kulkarni. Software Engineer. Writer. Sports and Esports fan.
author_hobbies: Playing Ukulele and writing blogs which make a difference to our world are some of my major hobbies. Apart from that I like to play and watch sports and esports. Whenever I get time, I stream all my gameplay at twitch.tv/inflatonn.

author_work_experiences:
            - company_name: Cobalt Speech and Language
              company_logo: Cobalt+Logo.jpg
              company_url: https://www.cobaltspeech.com/
              designation: Research Intern
              description: Worked on various ASR and TTS engines
              visibility: true
            - company_name: Salesforce
              company_logo: salesforce.png
              company_url: https://www.salesforce.com/
              designation: Data Analyst Intern
              description: Worked on various SFDC solutions and Einstien engine
              visibility: true
            - company_name: SixteenZero Analytics
              company_logo: sz.png
              company_url: https://sixteenzero.net/
              designation: Web development Intern
              description: Worked on the client side website
              visibility: true
            - company_name: Blue Banyan Technologies
              company_logo: bb.png
              company_url: https://www.bluebanyan.co.in/
              designation: Web development Intern
              description: Worked on various projects revolving web development
              visibility: true
            - company_name: AIESEC St.Petersburg
              company_logo: aiesec.jpeg
              company_url: https://aiesec.org/
              designation: Winter Intern
              description: Worked as a Java and English teacher to Russian students
              visibility: true

author_education_details:
              - college_logo: uta.png
                college_name: University of Texas at Arlington
                college_url: https://www.uta.edu/
                college_degree: Masters in Computer Science
                description: Machine learning and Artificial Intelligence specialization
                visibility: true
              - college_logo: vit.png
                college_name: Vellore Instituite of Technology
                college_url: https://vit.ac.in/
                college_degree: Bachelor of Technology
                description: Information and Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: inflatonn
github_username:  AthuOfficial
facebook_username: inflatonn
linkedin_username: inflatonn
#behance_username: johndoe
instagram_username: inflatonn
medium_username: inflatonn
twitch_username: inflatonn
spotify_username: athuofficial
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

#disqus_shortname: inflatonn
hyvor_talk_website_id: 857

# wakatime username (coding activity)
wakatime_username: inflatonn

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: atharvak56@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
